#
# Executes commands at the start of an interactive session.
#

# so you dont have to link the packages every time in development
export PACKAGE_DIRS=~/Code/meteor/PACKAGES
export NEO4J_PATH=/usr/local/Cellar/neo4j/2.1.7

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# alias usc="ssh corcos@aludra.usc.edu"
alias usc="ssh corcos@cs-server.usc.edu"


export SLIMERJSLAUNCHER=~/Applications/Firefox.app/Contents/MacOS/firefox


#export EDITOR=/Applications/TextEdit.app/Contents/MacOS/TextEdit
export EDITOR='vim'
# export EDITOR='subl'

# handy keybindings
bindkey "^A" beginning-of-line
bindkey "^E" end-of-line
bindkey "^R" history-incremental-search-backward
bindkey "^P" history-search-backward
bindkey "^Y" accept-and-hold
bindkey "^N" insert-last-word


alias clear4j="rm -rf /usr/local/Cellar/neo4j/2.1.7/libexec/data/graph.db"
alias cath="pygmentize -g"

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"

alias scan="arp -a"
alias mou="open -a Mou"

alias pi="ssh pi@raspberrypi.local"

# Show/hide hidden files in Finder
alias show="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hide="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Hide/show all desktop icons (useful when presenting)
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

# Ring the terminal bell, and put a badge on Terminal.app’s Dock icon
# (useful when executing time-consuming commands)
alias ring="tput bel"

alias gitclean="git rm -r --cached . && git add ."

alias edit="open -a TextEdit"

# LaTeX tools
export PATH=$PATH:/usr/texbin

# Wrapper with the robot voice :)
function talk() {
	say $1 -v Zarvox
}

function fs() {
  fastosphere search $1 -g
}

function notify() {
  /usr/bin/osascript -e "display notification \"$*\""
}

alias down="cd ~/Code/meteor/down"

alias ior="cd ~/Research/ior"
alias webtech="cd /Users/chet/Documents/Academic/G\ School/Grad\ School\ Classes/CSCI571\ -\ Web\ Tech"
export NODE_PATH=/usr/local/lib/node_modules

export PATH=$PATH:~/bin

alias pipupdate="sudo pip-review --interactive"

alias server="python -m SimpleHTTPServer 8080"

alias simulator='open /Applications/Xcode.app/Contents/Developer/Applications/iOS\ Simulator.app'


# git config --global push.default current
alias ga="git add ."
alias gcm="git commit -m"
alias gp="git push"
alias gs="git status"
alias gb="git branch"
alias gcb="git checkout"
